spring.application.name=my-portfolio-backend
spring.datasource.url=jdbc:postgresql://ep-solitary-resonance-a4kgn9x7-pooler.us-east-1.aws.neon.tech/portfolio?user=neondb_owner&password=npg_PV4sc9khmBeY&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_PV4sc9khmBeY
spring.datasource.hikari.maximun-pool-size=10
spring.datasource.connection-timeout=20000
spring.sql.init.mode=never
file.upload.dir=src/main/resources/static/img/projects
#importante para que Spring sirva lo que se escribe en disco SIN reiniciar
spring.web.resources.static-locations=classpath:/static/,file:src/main/resources/static/